name: Promote Cypress to Main

on:
  push:
    branches:
      - cypress

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout target branch 'main'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Switch to 'main' branch and reset to match 'origin/cypress'
      - name: Reset promotion branch
        run: |
          git status
          git checkout main                     # Ensure we're on main
          git status
          git reset --hard origin/cypress       # Force main to match cypress
          git status
          
      # Step 3: Create the pull request (cypress -> main)
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.MY_GITHUB_PAT }}
          branch: promote-to-main-${{ github.run_number }}
          title: Promote Cypress to Main
          commit-message: Promote Cypress to Main
          delete-branch: true
          draft: false
          maintainer-can-modify: true
          body: |
            🚀 Automated promotion from `cypress` to `main`
            ✅ Please review and merge.
          labels: |
            promote
            automated-pr
